[package]
name = "hello_halide"
version = "0.1.0"
edition = "2024"

[build-dependencies]
bindgen = "0.72.1"

[dependencies]
ndarray = "0.16"
pyo3 = { version = "0.22", features = ["extension-module"] }
numpy = "0.22"
rand = "0.9.2"
